name: Deploy Infrastructure

on:
  push:
    branches:
      - master

env:
  ENVIRONMENT: development
  AWS_REGION: us-east-1

jobs:
  deploy-client:
    name: Deploy client application
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test
      - id: login-aws
        name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: ls
      - name: Generate build
        run: |
          echo "Configure and build application"  \
          REACT_APP_AWS_REGION=${{ secrets.REACT_APP_AWS_REGION }} \
          REACT_APP_COGNITO_USER_POOL_ID=$(aws ssm get-parameter --name "/${{ env.ENVIRONMENT }}/CognitoUserPoolId" --query "Parameter.Value" --output text) \
          REACT_APP_COGNITO_APP_CLIENT_ID=$(aws ssm get-parameter --name "/${{ env.ENVIRONMENT }}/CognitoClientId" --query "Parameter.Value" --output text) \
          npm run build
      - name: Locate distribution ID
        run: |
          ID=$(aws cloudfront list-distributions \
          --query "DistributionList.Items[?Origins.Items[?Id=='clientAppS3Origin']].Id" \
          --output text)
          echo "DISTRIBUTION_ID=$(echo $ID)" >> $GITHUB_ENV
        shell: bash
      - name: Print distribution
        run: echo $DISTRIBUTION_ID
      - run: ls
      - name: Deploy to AWS
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ env.ENVIRONMENT }}-client-app-${{ steps.login-aws.outputs.aws-account-id }}
          bucket-region: ${{ env.AWS_REGION }}
          delete-removed: true
          private: true
          dist-id: ${{ env.DISTRIBUTION_ID }}
          invalidation: /