name: Deploy Infrastructure

on:
  push:
    branches:
      - master

env:
  ENVIRONMENT: development
  AWS_REGION: us-east-1

jobs:
  deploy-infrastructure:
    name: Deploy Infrastructure
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test
      - name: Generate build
        run: npm run build
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Locate distribution ID/
        run: |
          ID=$(aws cloudfront list-distributions \
          --query "DistributionList.Items[?Origins.Items[?Id=='clientAppS3Origin']].Id" \
          --output text)
          echo "DISTRIBUTION_ID=$(echo $ID)" >> $GITHUB_ENV
        shell: bash
      - name: Test
        run: echo $DISTRIBUTION_ID
      - name: Deploy to AWS
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ env.ENVIRONMENT }}-client-app
          bucket-region: ${{ env.AWS_REGION }}
          delete-removed: true
          private: true
          dist-id: ${{ env.DISTRIBUTION_ID }}
          invalidation: /